# Generated by Django 4.2.7 on 2024-08-25 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='task.customer'),
            preserve_default=False,
        ),
    ]
