# Generated by Django 5.0.7 on 2024-08-29 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_note_text_alter_note_title'),
        ('task', '0008_task_priority'),
    ]

    operations = [
    ]
