# Generated by Django 5.0.7 on 2024-08-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_merge_20240829_0641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-priority', '-stage', 'id']},
        ),
        migrations.AlterField(
            model_name='task',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], null=True),
        ),
    ]
