# Generated by Django 4.2.7 on 2024-08-29 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_alter_task_options_alter_task_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completion_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
