# Generated by Django 4.2.7 on 2024-08-29 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_alter_task_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completion_date',
            field=models.DateField(default=datetime.date(2024, 8, 29)),
        ),
    ]
