# Generated by Django 5.0.7 on 2024-08-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_alter_task_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
