# Generated by Django 5.0.7 on 2024-08-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_alter_task_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isFlagged',
            field=models.BooleanField(default=False),
        ),
    ]
